title: Agil Hummatli
description: Backend Developer | Systems Thinker | Learning in Public
author: Agil Hummatli
url: "https://agilhummatli.github.io"

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Social
github_username: AgilHummatli
linkedin_username: hummatliagil

# Build settings
markdown: kramdown
highlighter: rouge
